images:
  - name: quay.io/herringbone/operations-center
    newTag: 1e94eaf3
    digest: "sha256:afe507893c8550841e35662a1db1704c72ae2d6c3613f144ebf7bc43ecb9514a"
resources:
  - deployment.yaml
  - service.yaml
