images:
  - name: quay.io/herringbone/operations-center
    newTag: 15926a80
    digest: "sha256:30b079d8c77f0fc07bc419601c67f1c087da373c9f56a16cb9b2ed8d0c20f9cf"
resources:
  - deployment.yaml
  - service.yaml
