services:
  operations-center:
    image: quay.io/herringbone/operations-center:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      VITE_HERRINGBONE_API_BASE: "http://127.0.0.1"