apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-f409f301-58
    digest: sha256:a7d3204356995be701d3612ec722521cddc35fe187c195223535299770bb5db2
