apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-a1aaa53d-38
    digest: sha256:c9af3ee3e3c00f9a868836dd20caa193255179f5c4e40fdf602c0505d49e45f2
