apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-7875e7a2-10
    digest: sha256:4a45ca542710d82f1889386da581cded5265ecd6931966c4015b20d321a06a45
