apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-55fdc234-79
    digest: sha256:38ab9eff2306de36c6ab51b7f7a38037415aa3f5c80f90380dc07297e2b5489b
