apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-9e2772a3-28
    digest: sha256:1d1d396a7229180cd351513e46f7e46d2108b7ee96658f24504add33f501a793
