apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-464bcc57-17
    digest: sha256:522809927ea4c342aea76260432b4dcf6f2f9100738172941bb5551912eae62b
