apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-365f6b3f-21
    digest: sha256:163960e8b8fcd9d84638c4d806ae1365ff328e833662595f86065b5fa6f3c42b
