apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-191f5ad9-115
    digest: sha256:446f096e28c674e12acd468d4597f8eda95a9507e4cf32c5312d82005cfbab0c
