apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/commandpost
    newTag: latest-d5701b79-3
    digest: sha256:9cb51cea20972a47493ec917cdbc4719802e496b3be755e077708d4ad5c56fb3
