apiVersion: v1
kind: Service
metadata:
  name: herringbone-commandpost-service
  namespace: herringbone
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: herringbone-commandpost
  ports:
    - name: tcp
      protocol: TCP
      port: 5000
      targetPort: 5000