name: Docker Cleanup
description: Remove local Docker build cache and unused images.

runs:
  using: composite
  steps:
    - name: Cleanup Docker
      shell: bash
      run: docker system prune -af || true
