name: (Commandpost) Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'commandpost/**'
      - '.github/workflows/commandpost.yml'

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install yq
        run: |
          set -euo pipefail
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Set SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay (using your DOCKER_* secrets)
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}   # must be a Quay user or robot (e.g., herringbone+pushbot)
          password: ${{ secrets.DOCKER_PASSWORD }}   # Quay robot token or user CLI token

      # Build AND push in one step (avoids tag mismatches)
      - name: Build & Push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./commandpost
          file: ./commandpost/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            quay.io/herringbone/commandpost:latest
            quay.io/herringbone/commandpost:latest-${{ env.SHORT_SHA }}-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update kustomization.yaml with new image tag & digest
        run: |
          set -euo pipefail
          TAG="latest-${SHORT_SHA}-${GITHUB_RUN_NUMBER}"
          DIGEST="${{ steps.build.outputs.digest }}"
          yq eval -i ".images[0].newTag = \"${TAG}\"" kustomize/commandpost/kustomization.yaml
          yq eval -i ".images[0].digest = \"${DIGEST}\"" kustomize/commandpost/kustomization.yaml

      - name: Detect changes
        id: bump
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR (only if changes exist)
        if: steps.bump.outputs.changed == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(Commandpost): bump image to ${{ steps.build.outputs.digest }}"
          title: "chore(Commandpost): bump Commandpost image"
          body: |
            Automated update to kustomization for Commandpost image.
            - Tag & digest updated by CI
            - This PR respects branch protection.
          branch: auto/update/commandpost
          delete-branch: true
          signoff: true
          labels: automation

      - name: Log PR result
        if: steps.bump.outputs.changed == 'true'
        run: |
          echo "operation=${{ steps.cpr.outputs.pull-request-operation }}"
          echo "pr=${{ steps.cpr.outputs.pull-request-number || 'none' }}"

      - name: No changes
        if: steps.bump.outputs.changed != 'true'
        run: echo "No changes; skipping PR."