name: Build, Push & Sign Operations Center UI

on:
  push:
    branches: [ main ]
    paths:
      - 'operations-center/**'
      - '.github/workflows/operations-center.yml'

permissions:
  contents: write
  id-token: write
  pull-requests: write
  checks: write

jobs:
  build-ui:
    uses: ./.github/workflows/build-test-push-sign.yml
    secrets: inherit
    with:
      service_name: operations-center
      service_path: operations-center
      dockerfile: operations-center/docker/Dockerfile
      kustomization_path: kustomization/operations-center/kustomization.yaml
      image_repo: quay.io/herringbone/operations-center
